openapi: '3.0.2'
info:
    title: KitCoin API
    version: '1.0'
servers:
    - url: /api
paths:
    /api/balance/:user:
        get:
            description: Get user balance
            parameters:
                - name: user
                  in: path
                  description: Mongo User ID or `me` for logged in user
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: User balance
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    balance:
                                        type: number
    /api/transactions/:user:
        get:
            description: Get user transactions
            parameters:
                - name: user
                  in: path
                  description: Mongo User ID or `me` for logged in user
                  required: true
                  schema:
                      type: string
                - name: count
                  in: query
                  description: Number of transactions to return
                  required: false
                  schema:
                      type: integer
                - name: page
                  in: query
                  description: Page number
                  required: false
                  schema:
                      type: integer
            responses:
                200:
                    description: Array of user transactions
                    content:
                        application/json:
                            schema:
                                $ref: '../../../../schema/transactionapires.json'
        post:
            description: Create a new transaction
            parameters:
                - name: user
                  in: path
                  description: Mongo User ID
                  required: true
                  schema:
                      type: string
                - name: amount
                  in: query
                  description: Amount of transaction
                  required: true
                  schema:
                      type: number
                - name: type
                  in: query
                  description: Type of transaction
                  required: true
                  schema:
                      type: string
                - name: description
                  in: query
                  description: Description of transaction
                  required: false
                  schema:
                      type: string
            responses:
                200:
                    description: Created transaction
                    content:
                        application/json:
                            schema:
                                $ref: '../../../../schema/transactionapires.json'
