openapi: '3.0.2'
info:
    title: KitCoin API
    version: '1.0'
servers:
    - url: /api
paths:
    /api/balance/:user:
        get:
            description: Get user balance
            parameters:
                - name: user
                  in: path
                  description: Mongo User ID or `me` for logged in user
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: User balance
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    balance:
                                        type: number
    /api/transactions/:user:
        get:
            description: Get user transactions
            parameters:
                - name: user
                  in: path
                  description: Mongo User ID or `me` for logged in user
                  required: true
                  schema:
                      type: string
                - name: count
                  in: query
                  description: Number of transactions to return
                  required: false
                  schema:
                      type: integer
                - name: page
                  in: query
                  description: Page number
                  required: false
                  schema:
                      type: integer
            responses:
                200:
                    description: Array of user transactions
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    properties:
                                        amount:
                                            type: number
                                        reason:
                                            type: string
                                            nullable: true
                                        from:
                                            type: object
                                            properties:
                                                id:
                                                    type: string
                                                    nullable: true
                                                    description: Mongo User ID
                                                name:
                                                    type: string
                                                    nullable: true
                                                    description: Text to display (for non-user transactions)
                                        to:
                                            type: object
                                            properties:
                                                id:
                                                    type: string
                                                    nullable: true
                                                    description: Mongo User ID
                                                name:
                                                    type: string
                                                    nullable: true
                                                    description: Text to display (for non-user transactions)
                                        date:
                                            type: string
                                            format: date-time
                                            description: Date of transaction
